name: Test FastAPI Docker App in Subdirectory

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install test dependencies
      run: |
        pip install requests pytest

    - name: Build Docker Image
      run: docker build -t sl-maas-nvg ./nvg-endpoint

    - name: Run Docker Container
      run: docker run -d -p 8000:8000 --name sl-maas-nvg-container sl-maas-nvg

    - name: Wait for API to be Ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8000/docs; then
            echo "API is up!"
            break
          fi
          echo "Waiting for API..."
          sleep 3
        done

    - name: Run tests
      run: pytest tests/

    - name: Cleanup
      run: |
        docker stop sl-maas-nvg-container
        docker rm sl-maas-nvg-container